#version: '1.0'
#services:
#  app:
#    container_name: app-thc-springboot
#    image: app-thc-springboot
#    build: ./
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/thcApp
#      - SPRING_DATASOURCE_USERNAME=test
#      - SPRING_DATASOURCE_PASSWORD=test
#
#  db:
#    platform: linux/x86_64
#    image: mysql:8.0.27
#    container_name: db
#    ports:
#      - "3305:3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD=rootroot
#      - MYSQL_USER=test
#      - MYSQL_PASSWORD=test
#      - MYSQL_DATABASE=thcApp
#    command: mysqld --innodb_use_native_aio=0