version: '1.0'
services:
  db:
    image: mysql:8.0.29
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=thcApp
    ports:
      - 3305:3306
    networks:
      - mynetwork
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    ports:
      - 9201:9200
    environment:
      - node.name=Parimis-MacBook-Air.local
      - cluster.name=elasticsearch
    networks:
      - es-net
  kib:
    image: docker.elastic.co/kibana/kibana:8.2.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    networks:
      - es-net
    depends_on:
      - es
    ports:
      - 5602:5601
  app:
    build: ./
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/thcApp?useSSL=false&allowPublicKeyRetrieval=true
    networks:
      - mynetwork
networks:
  mynetwork:
    name: custom_network
  es-net:
    driver: bridge