version: '1.0'
services:
  db:
    image: mysql:8.0.29
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=thcApp
    ports:
      - 3306:3306
    networks:
      - mynetwork
  app:
    build: ./
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/thcApp?useSSL=false&allowPublicKeyRetrieval=true
    networks:
      - mynetwork
networks:
  mynetwork:
    name: custom_network